services:
  pve-mcp:
    build:
      context: ../mcp
      dockerfile: Dockerfile
    image: pve-mcp:latest
    container_name: pve-management-agent
    ports:
      - 8000:8000
    restart: always
    env_file:
      - .env
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rule.yml:/etc/prometheus/rule.yml
    secrets:
      - prometheus_token
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitor-net

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/config.yml
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    networks:
      - monitor-net
    
  prometheus_pusher:
    build:
      context: ./pusher
      dockerfile: Dockerfile
    image: prometheus-pusher:latest
    container_name: prometheus_pusher
    restart: unless-stopped
    ports:
      - "9095:9095" 
    volumes:
      - ./pusher/prometheus_pusher.py:/app/prometheus_pusher.py 
    environment:
      PVE_AGENT_ALERT_URL: "http://agent:9999/chat"
    networks:
      - monitor-net

  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    image: agent:latest
    container_name: agent
    restart: unless-stopped
    ports:
      - "9999:9999"
    volumes:
      - ./agent/prompt.txt:/app/prompt.txt
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: 1
    networks:
      - monitor-net  

networks:
  monitor-net:
    driver: bridge

secrets:
  prometheus_token:
    file: ./prometheus/token
