services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/token:/etc/prometheus/token
      - ./prometheus/rule.yml:/etc/prometheus/rule.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/config.yml
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    networks:
      - monitor-net
    
  prometheus_pusher:
    build:
      context: ./pusher
      dockerfile: Dockerfile
    image: prometheus-pusher:latest
    container_name: prometheus_pusher
    restart: unless-stopped
    ports:
      - "9095:9095" 
    volumes:
      - ./pusher/prometheus_pusher.py:/app/prometheus_pusher.py 
    environment:
      PVE_AGENT_ALERT_URL: "http://{{AGENT_HOST}}:9999/chat"
    networks:
      - monitor-net

  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    image: pve-agent:latest
    container_name: agent
    restart: unless-stopped
    ports:
      - "9999:9999"
    environment:
      DEEPSEEK_API_KEY: "DEEPSEEK_API_KEY_VALUE"
      MCP_URL: "http://{{MCP_HOST}}:8000/mcp"
    networks:
      - monitor-net  

networks:
  monitor-net:
    driver: bridge
