services:
  pve-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: pve-mcp:latest
    container_name: pve-management-agent
    ports:
      - 8000:8000
    restart: always
    env_file:
      - .env