#cloud-config
users:
  - name: bisheng
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
chpasswd:
  list: |
    bisheng:password
  expire: false
ssh_pwauth: true

package_update: true
package_upgrade: true
packages:
  - curl
  - qemu-guest-agent
  - nfs-server

runcmd:
  - systemctl enable --now qemu-guest-agent
  - |
    export MANAGER_IP="192.168.116.100" 
    wget http://${MANAGER_IP}:8080/init.sh
    wget http://${MANAGER_IP}:8080/nodeexporter/set_node_exporter.sh
    chmod +x init.sh
    chmod +x set_node_exporter.sh
    bash init.sh control_node
    bash set_node_exporter.sh
