global:
  resolve_timeout: 5m

route:
  receiver: 'default-receiver'

  group_by: ['alertname', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

  routes:
  - receiver: 'pve-agent-receiver'
    match:
      severity: 'critical'
    continue: true
  - receiver: 'test-receiver'
    match:
      severity: 'test'
    continue: true

receivers:
  - name: 'default-receiver'
  - name: 'test-receiver'
    webhook_configs:
    - url: 'http://prometheus_pusher:9095/webhook/alertmanager'
      send_resolved: true
  - name: 'pve-agent-receiver'
    webhook_configs:
    - url: 'http://prometheus_pusher:9095/webhook/alertmanager'
      send_resolved: true